---
title: "R Notebook"
output: html_notebook
---
Testando e aprendendo comandos R.
Criando ums estrutura do tipo dataFrame e executando uma plotagem, scatter plot, das colunas "ACT"vs"Year".
```{r}

austpop <- structure(
  list(
    Year = c(1917, 1927, 1937, 1947, 1957, 1967, 1977, 1987, 1997),
    NSW = c(1904, 2402, 2693, 2985, 3625, 4295, 5002,5617, 6274),
    Vic. = c(1409, 1727, 1853, 2055, 2656, 3274, 3837,4210, 4605), 
    Qld = c(683, 873, 993, 1106, 1413, 1700, 2130, 2675,3401),
    SA = c(440, 565, 589, 646, 873, 1110, 1286, 1393, 1480),
    WA = c(306, 392, 457, 502, 688, 879, 1204, 1496, 1798),
    Tas. = c(193,211, 233, 257, 326, 375, 415, 449, 474),
    NT = c(5, 4, 6, 11,21, 62, 104, 158, 187),
    ACT = c(3, 8, 11, 17, 38, 103, 214, 265,310),
    Aust. = c(4941, 6182, 6836, 7579, 9640, 11799, 14192, 16264,18532)
    ),
  .Names = c("Year", "NSW", "Vic.", "Qld", "SA", "WA","Tas.", "NT", "ACT", "Aust."),
  class = "data.frame",
  row.names = c("1", "2", "3", "4", "5", "6", "7", "8", "9")
  )

# Plotagem
plot(ACT ~ Year, data=austpop, pch=16)


```

Apresentando os nomes das colunas.
```{r}
names(austpop)
```

Entrando com outros dados.

```{r}

elasticband <- data.frame(
  stretch=c(46,54,48,50,44,42,52),
  distance=c(148,182,173,166,109,141,166)
)

elasticband <- edit(elasticband) #Muito interessante para entrada rápida e manual

```

Comandos para ajuda.

```{r}

help(plot)
apropos("plot") #muito útil. Lista todas as funções com a palavra no argumento.
help.search("matrix")
```


Alguns exemplos básicos:

```{r}
names(elasticband)
plot(distance ~ stretch, data=elasticband, pch=16)

```




```{r}

dataSnow <- data.frame(
  year = c(1970:1979),
  snow.cover = c(6.5, 12.0, 14.9, 10.0, 10.7, 7.9, 21.9, 12.5, 14.5, 9.2)
)

plot(snow.cover ~ year, data=dataSnow, pch=16)
hist(dataSnow$snow.cover)
```


















